export default [
  {
    key: 'index',
    route: 'docs-getting-started-id',
    url: 'docs/getting-started',
    label: 'Getting started',
    items: [
      { key: 'quick-start', label: 'Quick start' },
      { key: 'custom-builds', label: 'Custom builds' },
      { key: 'theming', label: 'Theming' },
      { key: 'migration', label: 'Migration' },
    ],
  },
  {
    key: 'index',
    route: 'docs-components-id',
    url: 'docs/components',
    label: 'Components',
    items: [
      { key: 'accordion', label: 'Accordion' },
      { key: 'alert', label: 'Alert' },
      { key: 'button', label: 'Button' },
      { key: 'button-group', label: 'Button group' },
      { key: 'collapse', label: 'Collapse' },
      { key: 'collection', label: 'Collection' },
      { key: 'footer', label: 'Footer' },
      { key: 'form', label: 'Form' },
      { key: 'grid', label: 'Grid' },
      { key: 'line', label: 'Line' },
      { key: 'loader', label: 'Loader' },
      { key: 'modal', label: 'Modal' },
      { key: 'navbar', label: 'Navbar' },
      { key: 'notification', label: 'Notification' },
      { key: 'off-canvas', label: 'Off-Canvas' },
      { key: 'progress', label: 'Progress' },
      { key: 'selectbox', label: 'Selectbox' },
      { key: 'tab', label: 'Tab' },
      { key: 'tile', label: 'Tile' },
      { key: 'table', label: 'Table' },
    ],
  },
  {
    key: 'index',
    route: 'docs-utilities-id',
    url: 'docs/utilities',
    label: 'Utilities',
    items: [
      { key: 'borders', label: 'Borders' },
      { key: 'clearfix', label: 'Clearfix' },
      { key: 'icons', label: 'Icons' },
      { key: 'colors', label: 'Colors' },
      { key: 'display', label: 'Display' },
      { key: 'embed', label: 'Embed' },
      { key: 'flex', label: 'Flex' },
      { key: 'float', label: 'Float' },
      { key: 'fonts', label: 'Fonts' },
      // { key: 'network', label: 'Network' }, // @todo enable?
      { key: 'position', label: 'Position' },
      { key: 'screen-readers', label: 'Screen readers' },
      { key: 'shadow', label: 'Shadow' },
      { key: 'sizing', label: 'Sizing' },
      { key: 'spacing', label: 'Spacing' },
      { key: 'text', label: 'Text' },
      { key: 'unselectable', label: 'Unselectable' },
      { key: 'vertical-align', label: 'Vertical Align' },
      { key: 'visibility', label: 'Visibility' },
    ],
  },
];
